title: "Google Apps Script(GAS)を使い倒して、月次アンケート作成を自動化した話"
summary: ""
topics: ["gas", "graphql", "restapi", "deepl", "kibela"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - introduction
  - google-spread-sheet
  - kibela
  - deepl
  - google-form
  - conclusion
